// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
)

type CronSchedule struct {
	Expression string `json:"expression"`

	AdditionalProperties interface{} `json:"-"`
}
type _CronSchedule CronSchedule

func (c *CronSchedule) UnmarshalJSON(bs []byte) error {
	data := _CronSchedule{}

	if err := json.Unmarshal(bs, &data); err != nil {
		return err
	}
	*c = CronSchedule(data)

	additionalFields := make(map[string]interface{})

	if err := json.Unmarshal(bs, &additionalFields); err != nil {
		return err
	}
	delete(additionalFields, "expression")

	c.AdditionalProperties = additionalFields

	return nil
}

func (c CronSchedule) MarshalJSON() ([]byte, error) {
	out := map[string]interface{}{}
	bs, err := json.Marshal(_CronSchedule(c))
	if err != nil {
		return nil, err
	}

	if err := json.Unmarshal([]byte(bs), &out); err != nil {
		return nil, err
	}

	bs, err = json.Marshal(c.AdditionalProperties)
	if err != nil {
		return nil, err
	}

	if err := json.Unmarshal([]byte(bs), &out); err != nil {
		return nil, err
	}

	return json.Marshal(out)
}
