// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ValidateErrorJSON struct {
	Details map[string]interface{}   `json:"details"`
	Message ValidateErrorJSONMessage `json:"message"`
}
