// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"bytes"
	"encoding/json"
	"errors"
)

type SyncUpdateScheduleScheduleType string

const (
	SyncUpdateScheduleScheduleTypeIntervalSchedule   SyncUpdateScheduleScheduleType = "IntervalSchedule"
	SyncUpdateScheduleScheduleTypeCronSchedule       SyncUpdateScheduleScheduleType = "CronSchedule"
	SyncUpdateScheduleScheduleTypeVisualCronSchedule SyncUpdateScheduleScheduleType = "VisualCronSchedule"
	SyncUpdateScheduleScheduleTypeDBTSchedule        SyncUpdateScheduleScheduleType = "DBTSchedule"
)

type SyncUpdateScheduleSchedule struct {
	IntervalSchedule   *IntervalSchedule
	CronSchedule       *CronSchedule
	VisualCronSchedule *VisualCronSchedule
	DBTSchedule        *DBTSchedule

	Type SyncUpdateScheduleScheduleType
}

func CreateSyncUpdateScheduleScheduleIntervalSchedule(intervalSchedule IntervalSchedule) SyncUpdateScheduleSchedule {
	typ := SyncUpdateScheduleScheduleTypeIntervalSchedule

	return SyncUpdateScheduleSchedule{
		IntervalSchedule: &intervalSchedule,
		Type:             typ,
	}
}

func CreateSyncUpdateScheduleScheduleCronSchedule(cronSchedule CronSchedule) SyncUpdateScheduleSchedule {
	typ := SyncUpdateScheduleScheduleTypeCronSchedule

	return SyncUpdateScheduleSchedule{
		CronSchedule: &cronSchedule,
		Type:         typ,
	}
}

func CreateSyncUpdateScheduleScheduleVisualCronSchedule(visualCronSchedule VisualCronSchedule) SyncUpdateScheduleSchedule {
	typ := SyncUpdateScheduleScheduleTypeVisualCronSchedule

	return SyncUpdateScheduleSchedule{
		VisualCronSchedule: &visualCronSchedule,
		Type:               typ,
	}
}

func CreateSyncUpdateScheduleScheduleDBTSchedule(dbtSchedule DBTSchedule) SyncUpdateScheduleSchedule {
	typ := SyncUpdateScheduleScheduleTypeDBTSchedule

	return SyncUpdateScheduleSchedule{
		DBTSchedule: &dbtSchedule,
		Type:        typ,
	}
}

func (u *SyncUpdateScheduleSchedule) UnmarshalJSON(data []byte) error {
	var d *json.Decoder

	intervalSchedule := new(IntervalSchedule)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&intervalSchedule); err == nil {
		u.IntervalSchedule = intervalSchedule
		u.Type = SyncUpdateScheduleScheduleTypeIntervalSchedule
		return nil
	}

	cronSchedule := new(CronSchedule)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&cronSchedule); err == nil {
		u.CronSchedule = cronSchedule
		u.Type = SyncUpdateScheduleScheduleTypeCronSchedule
		return nil
	}

	visualCronSchedule := new(VisualCronSchedule)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&visualCronSchedule); err == nil {
		u.VisualCronSchedule = visualCronSchedule
		u.Type = SyncUpdateScheduleScheduleTypeVisualCronSchedule
		return nil
	}

	dbtSchedule := new(DBTSchedule)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&dbtSchedule); err == nil {
		u.DBTSchedule = dbtSchedule
		u.Type = SyncUpdateScheduleScheduleTypeDBTSchedule
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u SyncUpdateScheduleSchedule) MarshalJSON() ([]byte, error) {
	if u.IntervalSchedule != nil {
		return json.Marshal(u.IntervalSchedule)
	}

	if u.CronSchedule != nil {
		return json.Marshal(u.CronSchedule)
	}

	if u.VisualCronSchedule != nil {
		return json.Marshal(u.VisualCronSchedule)
	}

	if u.DBTSchedule != nil {
		return json.Marshal(u.DBTSchedule)
	}

	return nil, nil
}

// SyncUpdateSchedule - The scheduling configuration. It can be triggerd based on several ways:
//
// Interval: the sync will be trigged based on certain interval(minutes/hours/days/weeks)
//
// Cron: the sync will be trigged based on cron expression https://en.wikipedia.org/wiki/Cron.
//
// Visual: the sync will be trigged based a visual cron configuration on UI
//
// DBT-cloud: the sync will be trigged based on a dbt cloud job
type SyncUpdateSchedule struct {
	Schedule SyncUpdateScheduleSchedule `json:"schedule"`
	Type     string                     `json:"type"`
}

// SyncUpdate - The input for updating a Sync
type SyncUpdate struct {
	// The sync's configuration. This specifies how data is mapped, among other
	// configuration.
	//
	// The schema depends on the destination type.
	//
	// Consumers should NOT make assumptions on the contents of the
	// configuration. It may change as Hightouch updates its internal code.
	Configuration map[string]interface{} `json:"configuration,omitempty"`
	// Whether the sync has been disabled by the user.
	Disabled *bool `json:"disabled,omitempty"`
	// The scheduling configuration. It can be triggerd based on several ways:
	//
	// Interval: the sync will be trigged based on certain interval(minutes/hours/days/weeks)
	//
	// Cron: the sync will be trigged based on cron expression https://en.wikipedia.org/wiki/Cron.
	//
	// Visual: the sync will be trigged based a visual cron configuration on UI
	//
	// DBT-cloud: the sync will be trigged based on a dbt cloud job
	Schedule *SyncUpdateSchedule `json:"schedule,omitempty"`
}
