// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"bytes"
	"encoding/json"
	"errors"
	"hightouch/internal/sdk/pkg/models/shared"
	"net/http"
)

type CreateModel200ApplicationJSONType string

const (
	CreateModel200ApplicationJSONTypeModel               CreateModel200ApplicationJSONType = "Model"
	CreateModel200ApplicationJSONTypeValidateErrorJSON   CreateModel200ApplicationJSONType = "ValidateErrorJSON"
	CreateModel200ApplicationJSONTypeInternalServerError CreateModel200ApplicationJSONType = "InternalServerError"
)

type CreateModel200ApplicationJSON struct {
	Model               *shared.Model
	ValidateErrorJSON   *shared.ValidateErrorJSON
	InternalServerError *shared.InternalServerError

	Type CreateModel200ApplicationJSONType
}

func CreateCreateModel200ApplicationJSONModel(model shared.Model) CreateModel200ApplicationJSON {
	typ := CreateModel200ApplicationJSONTypeModel

	return CreateModel200ApplicationJSON{
		Model: &model,
		Type:  typ,
	}
}

func CreateCreateModel200ApplicationJSONValidateErrorJSON(validateErrorJSON shared.ValidateErrorJSON) CreateModel200ApplicationJSON {
	typ := CreateModel200ApplicationJSONTypeValidateErrorJSON

	return CreateModel200ApplicationJSON{
		ValidateErrorJSON: &validateErrorJSON,
		Type:              typ,
	}
}

func CreateCreateModel200ApplicationJSONInternalServerError(internalServerError shared.InternalServerError) CreateModel200ApplicationJSON {
	typ := CreateModel200ApplicationJSONTypeInternalServerError

	return CreateModel200ApplicationJSON{
		InternalServerError: &internalServerError,
		Type:                typ,
	}
}

func (u *CreateModel200ApplicationJSON) UnmarshalJSON(data []byte) error {
	var d *json.Decoder

	internalServerError := new(shared.InternalServerError)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&internalServerError); err == nil {
		u.InternalServerError = internalServerError
		u.Type = CreateModel200ApplicationJSONTypeInternalServerError
		return nil
	}

	validateErrorJSON := new(shared.ValidateErrorJSON)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&validateErrorJSON); err == nil {
		u.ValidateErrorJSON = validateErrorJSON
		u.Type = CreateModel200ApplicationJSONTypeValidateErrorJSON
		return nil
	}

	model := new(shared.Model)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&model); err == nil {
		u.Model = model
		u.Type = CreateModel200ApplicationJSONTypeModel
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u CreateModel200ApplicationJSON) MarshalJSON() ([]byte, error) {
	if u.InternalServerError != nil {
		return json.Marshal(u.InternalServerError)
	}

	if u.ValidateErrorJSON != nil {
		return json.Marshal(u.ValidateErrorJSON)
	}

	if u.Model != nil {
		return json.Marshal(u.Model)
	}

	return nil, nil
}

type CreateModelResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Ok
	CreateModel200ApplicationJSONOneOf *CreateModel200ApplicationJSON
	// Something went wrong
	InternalServerError *shared.InternalServerError
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Conflict
	ValidateErrorJSON *shared.ValidateErrorJSON
}
