// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"bytes"
	"encoding/json"
	"errors"
	"hightouch/internal/sdk/pkg/models/shared"
	"net/http"
)

type CreateSource200ApplicationJSONType string

const (
	CreateSource200ApplicationJSONTypeSource              CreateSource200ApplicationJSONType = "Source"
	CreateSource200ApplicationJSONTypeValidateErrorJSON   CreateSource200ApplicationJSONType = "ValidateErrorJSON"
	CreateSource200ApplicationJSONTypeInternalServerError CreateSource200ApplicationJSONType = "InternalServerError"
)

type CreateSource200ApplicationJSON struct {
	Source              *shared.Source
	ValidateErrorJSON   *shared.ValidateErrorJSON
	InternalServerError *shared.InternalServerError

	Type CreateSource200ApplicationJSONType
}

func CreateCreateSource200ApplicationJSONSource(source shared.Source) CreateSource200ApplicationJSON {
	typ := CreateSource200ApplicationJSONTypeSource

	return CreateSource200ApplicationJSON{
		Source: &source,
		Type:   typ,
	}
}

func CreateCreateSource200ApplicationJSONValidateErrorJSON(validateErrorJSON shared.ValidateErrorJSON) CreateSource200ApplicationJSON {
	typ := CreateSource200ApplicationJSONTypeValidateErrorJSON

	return CreateSource200ApplicationJSON{
		ValidateErrorJSON: &validateErrorJSON,
		Type:              typ,
	}
}

func CreateCreateSource200ApplicationJSONInternalServerError(internalServerError shared.InternalServerError) CreateSource200ApplicationJSON {
	typ := CreateSource200ApplicationJSONTypeInternalServerError

	return CreateSource200ApplicationJSON{
		InternalServerError: &internalServerError,
		Type:                typ,
	}
}

func (u *CreateSource200ApplicationJSON) UnmarshalJSON(data []byte) error {
	var d *json.Decoder

	validateErrorJSON := new(shared.ValidateErrorJSON)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&validateErrorJSON); err == nil {
		u.ValidateErrorJSON = validateErrorJSON
		u.Type = CreateSource200ApplicationJSONTypeValidateErrorJSON
		return nil
	}

	internalServerError := new(shared.InternalServerError)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&internalServerError); err == nil {
		u.InternalServerError = internalServerError
		u.Type = CreateSource200ApplicationJSONTypeInternalServerError
		return nil
	}

	source := new(shared.Source)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&source); err == nil {
		u.Source = source
		u.Type = CreateSource200ApplicationJSONTypeSource
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u CreateSource200ApplicationJSON) MarshalJSON() ([]byte, error) {
	if u.ValidateErrorJSON != nil {
		return json.Marshal(u.ValidateErrorJSON)
	}

	if u.InternalServerError != nil {
		return json.Marshal(u.InternalServerError)
	}

	if u.Source != nil {
		return json.Marshal(u.Source)
	}

	return nil, nil
}

type CreateSourceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Ok
	CreateSource200ApplicationJSONOneOf *CreateSource200ApplicationJSON
	// Something went wrong
	InternalServerError *shared.InternalServerError
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Conflict
	ValidateErrorJSON *shared.ValidateErrorJSON
}
