// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"hightouch/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetModelRequest struct {
	// The id of the model
	ModelID float64 `pathParam:"style=simple,explode=false,name=modelId"`
}

type GetModelResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Ok
	Model *shared.Model
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
