// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"hightouch/internal/sdk/pkg/models/shared"
	"net/http"
)

type TriggerRunIDGraphRequest struct {
	TriggerRunIDGraphInput *shared.TriggerRunIDGraphInput `request:"mediaType=application/json"`
	GraphID                string                         `pathParam:"style=simple,explode=false,name=graphId"`
}

type TriggerRunIDGraphResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Ok
	TriggerRunIDGraphOutput *shared.TriggerRunIDGraphOutput
	// Validation Failed
	ValidateErrorJSON *shared.ValidateErrorJSON
}
